### ISSUE TITLE
error：Fetch and insert from NVD

### ISSUE THREAD

**Issue by WangSongsen** [kotakanbe/go-cpe-dictionary#24]
INFO[09-23|10:31:04] Fetch and insert from NVD... 
554401 / 554401 [----------------------------------------------------------------------------------------------------] 100.00% 5925 p/s
INFO[09-23|10:39:51] Inserted 0 CPEs 
INFO[09-23|10:39:51] Fetching...                              URL=https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2002.json.gz
INFO[09-23|10:39:51] Fetching...                              URL=https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2003.json.gz
2 / 2 [-----------------------------------------------------------------------------------------------------------------] 100.00% 1 p/s
CRIT[09-23|10:39:53] Failed to fetch.                         err="Failed to fetch nvd v3 feed. err : Failed to get feeds. err : [HTTP error. errs: [], url: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2003.json.gz HTTP error. errs: [], url: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2002.json.gz]"

What should i try to solve this problem

**Comment by BoraBak** [comment]
Hi @WangSongsen ,

I also came across with this error.
What I decided to do, is to use more updated versions of the data. The data is taken from [here](https://nvd.nist.gov/vuln/data-feeds).
So I changed the this: https://github.com/kotakanbe/go-cpe-dictionary/blob/8daf5a4a31eec25a488d5dac47d810a69b38a8f0/nvd/nvd.go#L145 
to be:
`formatTemplate := "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-%d.json.gz"`
Also, I changed this:
https://github.com/kotakanbe/go-cpe-dictionary/blob/8daf5a4a31eec25a488d5dac47d810a69b38a8f0/nvd/nvd.go#L106
to be:
`startYear := 2018`

This way, you'll work with the latest data. You can change those params to expend the data you want to work with.

Cheers 🍻

**Comment by kotakanbe** [comment]
Hi, @BoraBak @WangSongsen 

Fixed 👍
